name: advance_task_manager
description: A task manager, built with flutter for iOS and android devices

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqflite: ^2.0.2+1
  flutter_bloc: ^8.0.1
  font_awesome_flutter: ^10.1.0
  path: ^1.8.1
  path_provider: ^2.0.11
  gap: ^2.0.0
  flutter_local_notifications: ^9.6.0
  flutter_native_timezone: ^2.0.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  date_picker_timeline: ^1.2.3
  equatable: ^2.0.3
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
